version: "3"
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
      MONGO_INITDB_DATABASE: mydb
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - pendejoNetwork

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://mongo:mysecretpassword@db:27017/
    networks:
      - pendejoNetwork

volumes:
  db-data:


networks:
  pendejoNetwork:
